spring.application.name: Api-Gateway
server.port: 8888

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

jwt.secretKey: fjegqgv345gq3hfuqy4891ghfnef81yf34uh1fj891f849hqijfheuhc813ihecuhvq98hub
#eureka:
#  instance:
#    prefer-ip-address: true
spring:
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2


        - id: Post-Service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: Connection-Service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

